# Change these first
owner: iamthecloverly # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Sribalaji
    url: https://www.sribalaji.eu.org
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Techviz
    url: https://vsb.techviz.tech
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Drive
    url: https://cloud.sribalaji.eu.org
  - name: Portfolio
    url: https://iamsribalaji.in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sribalaji.eu.org
  # baseUrl: /monitor
  logoUrl: https://avatars.githubusercontent.com/u/86469621
  name: Status | Sribalaji
  introTitle: "**Status | Sribalaji** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [**GitHub repository**](https://github.com/iamthecloverly/monitor). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: LinkedIn
      href: https://www.linkedin.com/in/thecloverly
  theme: light
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
